"use client"
import { Inter } from 'next/font/google'
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css'
import { useEffect } from 'react'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   require('bootstrap/dist/js/bootstrap.bundle.min.js')
  // }, [])
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
